// Galactic Camp 2026 — Schedule Data
// All times are Pacific Daylight Time (PDT = UTC-7)
// Do not edit the rendering logic here; this file contains event data only.
// To update the schedule, add/edit/remove entries in SCHEDULE_EVENTS.
// The `id` field must never change after the site goes live (used as localStorage key for favorites).

window.SCHEDULE_EVENTS = [

  // ─────────────────────────────────────────────────────────────
  // FRIDAY, May 29, 2026
  // ─────────────────────────────────────────────────────────────

  {
    id: 'fri-dealers-den',
    displayDay: 'Friday',
    title: "Dealer's Den",
    startISO: '2026-05-29T11:00:00-07:00',
    endISO:   '2026-05-29T18:00:00-07:00',
    venue: 'Other',
    locationDetail: "Dealer's Den",
    category: 'Dealers Den',
    panelists: [],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-003',
    displayDay: 'Friday',
    title: 'Trash Panda Trashy Karaoke',
    startISO: '2026-05-29T13:00:00-07:00',
    endISO:   '2026-05-29T22:00:00-07:00',
    venue: 'Other',
    locationDetail: 'Apollo Exhibit',
    category: 'Other',
    panelists: ['CK9'],
    description: 'Do you suck at Karaoke? So do we! Come find our judgement-free zone, check your ego at the door, and sing your little furry heart out. In the bowels of this ship, no one cares if your awoo is on pitch!',
    featured: true,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-004',
    displayDay: 'Friday',
    title: 'Uno for Funny Animals',
    startISO: '2026-05-29T17:00:00-07:00',
    endISO:   '2026-05-29T18:30:00-07:00',
    venue: 'Panel Room C',
    category: 'Panel',
    panelists: ['Ziggy the Hamster'],
    description: 'Join Ziggy and other funny animals -- in suit and not -- for some lively games of Uno',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-006',
    displayDay: 'Friday',
    title: 'Opening Ceremonies',
    startISO: '2026-05-29T19:00:00-07:00',
    endISO:   '2026-05-29T19:30:00-07:00',
    venue: 'Main Stage',
    category: 'House Event',
    panelists: [],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-007',
    displayDay: 'Friday',
    title: 'Furry Scavenger Hunt',
    startISO: '2026-05-29T11:00:00-07:00',
    endISO:   '2026-05-29T18:00:00-07:00',
    venue: 'Other',
    locationDetail: "Dealer's Den: The Forsaken Scribe Booth",
    category: 'Interactive',
    panelists: ['Yin Yang the Dutch Angel Dragon', 'Adam the Ambitious', 'The Forsaken Scribe'],
    description: 'Navigate the USS Hornet in a whole new way! Grab a booklet, bingo card, and a set of clues, then collect stamps or photograph your finds as you explore the ship. Learn surprising facts about the Hornet, meet fellow campers along the way, and optionally take on bonus challenges for a prize from the hosts. This activity is best started on Day 1, but extras will be available Saturday and Sunday for those who can\'t make it Friday.\n\nCome by the The Forsaken Scribe Booth in the Dealer\'s Den to pick up your starter pack to begin your grand adventure!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-008',
    displayDay: 'Friday',
    title: 'After Dark Festival',
    startISO: '2026-05-29T20:00:00-07:00',
    endISO:   '2026-05-30T02:00:00-07:00',
    venue: 'Everywhere',
    category: null,
    panelists: [],
    description: 'Galactic Camp is 18+ this year; the entire venue is reserved for attendees during this block. No Photography / No Video. Gear allowed. Relaxed dress code (harnesses, leather, rubber/latex, pup hoods, etc). No nudity. Please respect the venue and the privacy of other attendees.',
    featured: true,
    babyfur: false,
    ageRestricted: '18+',
    status: 'confirmed',
  },

  {
    id: 'fri-009',
    displayDay: 'Friday',
    title: 'Adult Fursuit Games',
    startISO: '2026-05-29T20:00:00-07:00',
    endISO:   '2026-05-29T21:00:00-07:00',
    venue: 'Main Stage',
    category: 'Gaming',
    panelists: ['Cat Prowler'],
    description: 'Join us for more risque games with adult theme and toys. This is an R rated event that will be open to all with priority given to Fursuiters. If you wish to participate please arrive early — 40 person max.',
    featured: false,
    babyfur: false,
    ageRestricted: '18+',
    status: 'confirmed',
  },

  {
    id: 'fri-010',
    displayDay: 'Friday',
    title: 'Technology for Writers, Updated',
    startISO: '2026-05-29T19:30:00-07:00',
    endISO:   '2026-05-29T20:30:00-07:00',
    venue: 'Panel Room B',
    category: 'Panel',
    panelists: ['Blackfeather Tanfur'],
    description: 'An updated and expanded look at different technologies for use by writers. Previously presented at Further Confusion 2026, this version includes new tools and insights for anyone who writes — from hobbyists to published authors.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-011',
    displayDay: 'Friday',
    title: 'Jigsaw Puzzle Social',
    startISO: '2026-05-29T19:30:00-07:00',
    endISO:   '2026-05-29T21:30:00-07:00',
    venue: 'Panel Room C',
    category: 'Meetup',
    panelists: ['Zip the Stoat'],
    description: 'Come relax, make fur-riends, and connect while piecing together convention themed puzzles!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-012',
    displayDay: 'Friday',
    title: 'Starburst',
    startISO: '2026-05-29T20:00:00-07:00',
    endISO:   '2026-05-29T21:30:00-07:00',
    venue: 'Fantail',
    category: 'DJ',
    genre: 'Tropical / Melodic / Progressive House',
    panelists: [],
    description: 'Jus (Starburst Shark) is a Bay Area DJ who primarily spins mid-2010s House & Trance. Focusing on vocal and live-instrument heavy tracks, he brings the emotional, nostalgic, and yet invigorating feeling of summer all year-round.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-013',
    displayDay: 'Friday',
    title: 'Femme BabyFur Meet-up and Socials',
    startISO: '2026-05-29T20:00:00-07:00',
    endISO:   '2026-05-29T21:00:00-07:00',
    venue: 'Panel Room A',
    locationDetail: null,
    category: 'Meetup',
    panelists: ['Squeak'],
    description: 'For all non-men babyfurs! This includes all transfems, nonbinary folks (if they so choose), and cis women. Have fun connecting outside of male dominated spaces!',
    featured: false,
    babyfur: false,
    ageRestricted: '18+',
    status: 'confirmed',
  },

  {
    id: 'fri-015',
    displayDay: 'Friday',
    title: 'History of Space Exploration',
    startISO: '2026-05-29T21:00:00-07:00',
    endISO:   '2026-05-29T22:00:00-07:00',
    venue: 'Panel Room B',
    category: 'Panel',
    panelists: ['Lucas'],
    description: 'In this panel we will learn about the human exploration of space, from the early days of Sputnik and Mercury-Redstone to the Artemis missions of today!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },


  {
    id: 'fri-017',
    displayDay: 'Friday',
    title: 'DatGai',
    startISO: '2026-05-29T21:30:00-07:00',
    endISO:   '2026-05-29T23:00:00-07:00',
    venue: 'Fantail',
    category: 'DJ',
    genre: 'Anime and Japanese-Adjacent Remixes',
    panelists: [],
    description: 'DatGai is a J-Core/Anison DJ that works closely with AniClover, a non-profit organization dedicated to bringing the culture of anime clubs from Japan (anikura) to the Bay Area. You might have seen DatGai spinning at FanimeCon, Anime Los Angeles, and Crunchyroll Expo. His mission is to educate and share one of his favorite niches with fellow music enjoyers.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-020',
    displayDay: 'Friday',
    title: 'AB/DL Introductions!',
    startISO: '2026-05-29T21:30:00-07:00',
    endISO:   '2026-05-29T22:30:00-07:00',
    venue: 'Panel Room A',
    locationDetail: null,
    category: 'Panel',
    panelists: ['Tai'],
    description: 'Interested in AB/DL? From first timers, to crinklers and caregivers looking to make friends - all critters are welcome to hear a short introduction into our little world! Halfway through we\'ll shift into a meet-and-greet.',
    featured: false,
    babyfur: false,
    ageRestricted: '18+',
    status: 'confirmed',
  },

  {
    id: 'fri-018',
    displayDay: 'Friday',
    title: 'Ikkuma',
    startISO: '2026-05-29T23:00:00-07:00',
    endISO:   '2026-05-30T00:30:00-07:00',
    venue: 'Fantail',
    category: 'DJ',
    genre: 'Progressive Multigenre',
    panelists: [],
    description: 'Ikkuma hails from Santa Cruz, CA. DJing since the early 2000s, he has entertained crowds at many furry events including Further Confusion, PAWCon, BLFC, and plays regularly at Frolic in San Francisco. His style brings a wide variety of imminently dance-able tunes to the mix — a multi-genre and eclectic blend of house, big room, breaks, trance, and anything else that keeps the energy and the dance floor moving.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-019',
    displayDay: 'Friday',
    title: 'Omen',
    startISO: '2026-05-30T00:30:00-07:00',
    endISO:   '2026-05-30T02:00:00-07:00',
    venue: 'Fantail',
    category: 'DJ',
    genre: 'Progressive House / Deep House / Trance / Techno',
    panelists: [],
    description: 'DJ Omen is a trans furry and pup that has been in both communities for well over 12 years and loves to spread good vibes, awesome beats, and general awesomeness everywhere she goes. This Sea Lotter (sea lion/otter hybrid) is a talented DJ and Drag Queen and can\'t wait to bring her energy to the stage!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-fantail-bar',
    displayDay: 'Friday',
    title: 'Fantail Bar',
    startISO: '2026-05-29T19:00:00-07:00',
    endISO:   '2026-05-30T02:00:00-07:00',
    venue: 'Fantail',
    category: 'Bar',
    panelists: [],
    description: 'The Fantail Bar is open and serving drinks at the fantail.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-021',
    displayDay: 'Friday',
    title: 'Neon Bunny',
    startISO: '2026-05-29T21:00:00-07:00',
    endISO:   '2026-05-29T22:30:00-07:00',
    venue: 'Main Stage',
    category: 'DJ',
    genre: 'House / Tech House / Mainstream',
    panelists: [],
    description: 'You might know NeonBunny from other events such as Frolic, where he dj\'s just about every one. He\'s also dj\'d all over the SF Bay Area at a number of different events, including furry conventions, raves, street fairs, and more. His sound can range from deep dark tech house to more bubbly poppy house disco vibes.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-022',
    displayDay: 'Friday',
    title: 'CK9',
    startISO: '2026-05-29T22:30:00-07:00',
    endISO:   '2026-05-30T00:00:00-07:00',
    venue: 'Main Stage',
    category: 'DJ',
    genre: 'Dancefloor Drum & Bass',
    panelists: [],
    description: 'CK9 sets are a carefully calibrated mix of unhinged new takes on rave and pop classics, growling dirty bangers, and soaring moments of hug-your-friends catharsis. There\'s guaranteed to be a track you\'ll sing along to, a track you\'ll Shazam, and a track that\'ll get your paws further off the ground that you ever expected.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-023',
    displayDay: 'Friday',
    title: 'Gaj3tt',
    startISO: '2026-05-30T00:00:00-07:00',
    endISO:   '2026-05-30T02:00:00-07:00',
    venue: 'Main Stage',
    category: 'DJ',
    genre: 'Galactic Disco House',
    panelists: [],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-inflatabar',
    displayDay: 'Friday',
    title: 'InflataBar',
    startISO: '2026-05-29T19:00:00-07:00',
    endISO:   '2026-05-30T02:00:00-07:00',
    venue: 'Main Stage',
    category: 'Bar',
    panelists: [],
    description: 'The InflataBar is open and serving drinks at the main stage.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'fri-con-history',
    displayDay: 'Friday',
    title: '90 Years of Conventions: From 1936 to Today',
    startISO: '2026-05-29T18:30:00-07:00',
    endISO:   '2026-05-29T19:30:00-07:00',
    venue: 'Panel Room A',
    locationDetail: 'Petty Mess',
    category: 'Panel',
    panelists: ['Con History'],
    description: '90 years ago a group of New York and Philadelphia science fiction fans met up, starting the first convention. From there spawned the idea for Worldcon, the progenitor convention, from which would spring all comic, anime, media, Trekkie, brony, and yes even furry cons. Join us for a century long journey from First Fandom to fur fandom. Presented by Con History.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  // ─────────────────────────────────────────────────────────────
  // SATURDAY, May 30, 2026
  // ─────────────────────────────────────────────────────────────

  {
    id: 'sat-dealers-den',
    displayDay: 'Saturday',
    title: "Dealer's Den",
    startISO: '2026-05-30T11:00:00-07:00',
    endISO:   '2026-05-30T18:00:00-07:00',
    venue: 'Other',
    locationDetail: "Dealer's Den",
    category: 'Dealers Den',
    panelists: [],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-003',
    displayDay: 'Saturday',
    title: 'Change that diaper!',
    startISO: '2026-05-30T10:00:00-07:00',
    endISO:   '2026-05-30T10:30:00-07:00',
    venue: 'BabyFur Space',
    locationDetail: null,
    category: 'Panel',
    panelists: ['Honey Bear'],
    description: 'Need a change, get a change. Got a change, give a change!\nYou slept in that diaper all night, and now it\'s full and ready to be changed. No better way to make a new friend than to offer to change their diaper. Some come to this event where you can change and be changed!',
    featured: false,
    babyfur: true,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-001',
    displayDay: 'Saturday',
    title: 'Still Open',
    startISO: '2026-05-30T09:00:00-07:00',
    endISO:   '2026-05-30T11:00:00-07:00',
    venue: 'Main Stage',
    category: 'House Event',
    panelists: [],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-002',
    displayDay: 'Saturday',
    title: 'Whipcracking 101 - presentation',
    startISO: '2026-05-30T16:00:00-07:00',
    endISO:   '2026-05-30T16:30:00-07:00',
    venue: 'Panel Room B',
    category: 'Panel',
    panelists: ['Keyda Fynx'],
    description: 'Welcome to whips! This is an ALL AGES introduction to bullwhips. The first 20 minutes covers how whips are made, PPE, and safety. The presentation is then followed by a brief live demonstration and a hands-on whip cracking class. Safety equipment such as goggles and hearing protection will be provided.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-002b',
    displayDay: 'Saturday',
    title: 'Whipcracking 101 - demonstration',
    startISO: '2026-05-30T16:30:00-07:00',
    endISO:   '2026-05-30T17:30:00-07:00',
    venue: 'Other',
    locationDetail: 'Flight Deck',
    category: 'Panel',
    panelists: ['Keyda Fynx'],
    description: 'Welcome to whips! This is an ALL AGES introduction to bullwhips. The first 20 minutes covers how whips are made, PPE, and safety. The presentation is then followed by a brief live demonstration and a hands-on whip cracking class. Safety equipment such as goggles and hearing protection will be provided.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-004',
    displayDay: 'Saturday',
    title: 'Furry Scavenger Hunt',
    startISO: '2026-05-30T11:00:00-07:00',
    endISO:   '2026-05-30T18:00:00-07:00',
    venue: 'Other',
    locationDetail: "Dealer's Den: The Forsaken Scribe Booth",
    category: 'Interactive',
    panelists: ['Yin Yang the Dutch Angel Dragon', 'Adam the Ambitious', 'The Forsaken Scribe'],
    description: 'Navigate the USS Hornet in a whole new way! Grab a booklet, bingo card, and a set of clues, then collect stamps or photograph your finds as you explore the ship. Learn surprising facts about the Hornet, meet fellow campers along the way, and optionally take on bonus challenges for a prize from the hosts. This activity is best started on Day 1, but extras will be available Saturday and Sunday for those who can\'t make it Friday.\n\nCome by the The Forsaken Scribe Booth in the Dealer\'s Den to pick up your starter pack to begin your grand adventure!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-005',
    displayDay: 'Saturday',
    title: 'From Turing to Toasters: Artificial Intelligence\'s Past, Present, and Future',
    startISO: '2026-05-30T14:00:00-07:00',
    endISO:   '2026-05-30T15:00:00-07:00',
    venue: 'Panel Room A',
    category: 'Panel',
    panelists: ['Au Fay 翱非'],
    description: 'ChatGPT, DeepSeek, Gemini... You hear the names everywhere, but what is actually going on inside the black box? In this panel, we\'ll uncover the magic of AI. We\'ll explore how they work (at a high level — no math!), where they came from and where they are headed, and most importantly what they can (and can\'t) actually do. We\'ll also discuss the ethical and philosophical debates surrounding the technology. Join us for this intuitive introduction to the past, present, and future of Artificial Intelligence!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-006',
    displayDay: 'Saturday',
    title: 'From Apollo to Artemis: Fun Lunar Space History',
    startISO: '2026-05-30T12:30:00-07:00',
    endISO:   '2026-05-30T14:00:00-07:00',
    venue: 'Panel Room C',
    category: 'Panel',
    panelists: ['Doktor Wulf'],
    description: 'The Apollo program famously first landed astronauts on the moon in 1969, recovered them from the Pacific Ocean with this very ship, and repeated this feat successfully 5 more times. But what incredible efforts led to this accomplishment, why did we stop, and how does the Artemis program compare? We\'ll cover highlights of Apollo\'s challenges and accomplishments, lots of fun historical trivia and amusing bloopers, and some of what lies ahead in the new space race.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-007',
    displayDay: 'Saturday',
    title: 'Fursuit Runway',
    startISO: '2026-05-30T12:00:00-07:00',
    endISO:   '2026-05-30T13:00:00-07:00',
    venue: 'Other',
    locationDetail: 'Flight Deck',
    category: 'House Event',
    panelists: ['Cat Prowler'],
    description: 'Suiters join us on the flight deck and strut your stuff down an actual runway! Anyone wishing to participate please arrive 15 minutes early to fill out a bio/description card. All information must adhere to a \'PG\' rated standard.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-008',
    displayDay: 'Saturday',
    title: 'Fursuit Photo',
    startISO: '2026-05-30T13:30:00-07:00',
    endISO:   '2026-05-30T14:00:00-07:00',
    venue: 'Other',
    locationDetail: 'Main Stage (Secondary Area)',
    category: 'House Event',
    panelists: [],
    description: 'Please aim for 1:15 to get everyone in the shot, Photo shoot ends by 1:40 DON\'T BE LATE!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-009',
    displayDay: 'Saturday',
    title: 'Fursuit Games',
    startISO: '2026-05-30T14:00:00-07:00',
    endISO:   '2026-05-30T15:00:00-07:00',
    venue: 'Main Stage',
    category: 'House Event',
    panelists: ['Cat Prowler'],
    description: 'Tighten your tail and keep your paws on for some energetic games on the main stage.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-010',
    displayDay: 'Saturday',
    title: 'Novel Writing 101',
    startISO: '2026-05-30T14:00:00-07:00',
    endISO:   '2026-05-30T15:30:00-07:00',
    venue: 'Panel Room B',
    category: 'Panel',
    panelists: ['Kit Silver', 'Kyell Gold'],
    description: 'Join Kyell Gold for an introduction to the art of novel writing. From preparation and structure to maintaining momentum, this panel covers the key challenges and rewards of bringing a story to life. Perfect for aspiring writers and curious readers alike — practical insights and a behind-the-scenes look at the creative process.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-011',
    displayDay: 'Saturday',
    title: 'Open Mic / Rap Battle',
    startISO: '2026-05-30T15:00:00-07:00',
    endISO:   '2026-05-30T16:30:00-07:00',
    venue: 'Main Stage',
    category: 'Interactive',
    panelists: ['Dabk0ta'],
    description: 'Play an instrument? Think you\'ve got what it takes to command a mic in front of a crowd? Join us for an interactive show where you and your friends are the performers! Can you freestyle? Brave enough to try your hand at a battle or just showing off your skills? Try it with an improv live band!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-012',
    displayDay: 'Saturday',
    title: 'Beginner Poi Class',
    startISO: '2026-05-30T16:30:00-07:00',
    endISO:   '2026-05-30T18:00:00-07:00',
    venue: 'Other',
    locationDetail: 'Main Stage (Secondary Area)',
    category: 'Interactive',
    panelists: ['Crabs'],
    description: 'Ever wanted to learn how to spin those cool glowy things you see at raves? Well we\'ve got you covered! In this workshop, we will go over poi fundamentals and the basic moves to get you started. While this class is best suited for first timers and beginners, there will be a little something for everyone regardless of skill level. Sock poi will be provided, but feel free to bring your own if you\'ve got \'em.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-013',
    displayDay: 'Saturday',
    title: 'University Furs',
    startISO: '2026-05-30T15:30:00-07:00',
    endISO:   '2026-05-30T16:30:00-07:00',
    venue: 'Panel Room A',
    category: 'Panel',
    panelists: ['PortsNotAlt'],
    description: 'Furries? At my university? It\'s more likely than you think! Do you go to university? Want to talk and connect with furries of similar majors? Or maybe you\'d like to ask for advice for college or start a furry club at your school! If so, this is the panel for you!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-014',
    displayDay: 'Saturday',
    title: 'Radio Hacking and Electric Warfare',
    startISO: '2026-05-30T17:00:00-07:00',
    endISO:   '2026-05-30T18:00:00-07:00',
    venue: 'Panel Room B',
    category: 'Panel',
    panelists: ['NotPike'],
    description: 'Discussion of wireless technologies and security.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-015',
    displayDay: 'Saturday',
    title: 'Private Space Ventures and the New Space Race',
    startISO: '2026-05-30T15:00:00-07:00',
    endISO:   '2026-05-30T16:30:00-07:00',
    venue: 'Panel Room C',
    category: 'Panel',
    panelists: ['Doktor Wulf'],
    description: 'Lunar mining, harvesting asteroids worth billions, and casual space tourism — all previously distant fantasies, but now major business aspirations! On top of all this, a new space race is brewing, infusing nationalist passion and significant government funding. Let\'s talk about this world of New Space ventures, recent ups and downs in the market, and where this may all be headed. Who will get human settlement or robotic mining operations on the moon first?',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-017',
    displayDay: 'Saturday',
    title: 'AwooCru Car Show',
    startISO: '2026-05-30T11:00:00-07:00',
    endISO:   '2026-05-30T17:00:00-07:00',
    venue: 'Other',
    locationDetail: 'Pier',
    category: 'Interactive',
    panelists: ['SikDrift', 'AwooCru'],
    description: 'A truly unique crossover event where history, custom builds, and the furry community collide! A car show right next to the historic Hornet on the pier. Against the backdrop of historic aircraft and the San Francisco Bay, this is a meetup unlike any other.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-019',
    displayDay: 'Saturday',
    title: 'Sticker Swap',
    startISO: '2026-05-30T17:00:00-07:00',
    endISO:   '2026-05-30T19:00:00-07:00',
    venue: 'Panel Room C',
    category: 'Meetup',
    panelists: ['Sterling Noblewolf'],
    description: 'Bring your stickers, set up shop, and trade with your fellow furs! This is a meetup for trading any and all furry stickers. Sticker-able objects are also welcome to be brought and plastered with stickers!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-020',
    displayDay: 'Saturday',
    title: 'Freeze Tag',
    startISO: '2026-05-30T18:00:00-07:00',
    endISO:   '2026-05-30T19:00:00-07:00',
    venue: 'Other',
    locationDetail: 'Main Stage (Secondary Area)',
    category: 'Interactive',
    panelists: [],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-037',
    displayDay: 'Saturday',
    title: 'JavaScript Bad?',
    startISO: '2026-05-30T18:00:00-07:00',
    endISO:   '2026-05-30T19:00:00-07:00',
    venue: 'Panel Room A',
    locationDetail: 'Petty Mess',
    category: 'Panel',
    panelists: ['Joey Sparkletiger & Friends'],
    description: 'An open discussion on JavaScript, The Internet, and Computer Science.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-021',
    displayDay: 'Saturday',
    title: 'Lycan Cat',
    startISO: '2026-05-30T16:30:00-07:00',
    endISO:   '2026-05-30T18:00:00-07:00',
    venue: 'Main Stage',
    category: 'DJ',
    genre: 'Open Format',
    panelists: [],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-022',
    displayDay: 'Saturday',
    title: 'Decentralized Defense and the Future of War',
    startISO: '2026-05-30T19:00:00-07:00',
    endISO:   '2026-05-30T20:00:00-07:00',
    venue: 'Panel Room B',
    category: 'Panel',
    panelists: ['Diamond Dogs'],
    description: 'Diamond Dogs Group trains operators in the future of multi-domain warfare.\nThis is the founding story — why a West Point dropout, UC Berkeley graduate, and Yu-Gi-Oh world champion started a defense tech company in Silicon Valley\nWhat he actually thinks about AI, defense, personal sovereignty, and the cognitive warfare nobody wants to talk about honestly.\nNo NDAs. No PR filter. Drone bombs, combat medicine, edge AI, and why the most dangerous weapon is the one that decides what you\'re allowed to think.\nPotentially a giveaway of combat medic training for attendees (supplies limited)\nPresented by Michael Tsai, One of Marc Andreessen\'s Tech Rock Stars, Founder and CEO of Diamond Dogs Group',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-023',
    displayDay: 'Saturday',
    title: 'Chinese Language 101: 福瑞 (Fúruì)',
    startISO: '2026-05-30T20:30:00-07:00',
    endISO:   '2026-05-30T21:30:00-07:00',
    venue: 'Panel Room B',
    category: 'Panel',
    panelists: ['Au Fay 翱非'],
    description: '大家好 (Dàjiā hǎo)! Want to learn a few words for yipping and yapping in Chinese with fellow furries? Curious about how to describe your fursona\'s species, make animal sounds, or call your friends cute in Chinese? Join this panel and learn all about it! All levels welcome; no prior experience needed!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-024',
    displayDay: 'Saturday',
    title: 'SparkleFur Meetup',
    startISO: '2026-05-30T20:30:00-07:00',
    endISO:   '2026-05-30T21:30:00-07:00',
    venue: 'Panel Room C',
    category: 'Meetup',
    panelists: ['Squeak'],
    description: 'For all the colorful furries out there! We will have a Kandi trade table and tables to sit and meet your fellow sparklefurs! Have fun and remember PLURR!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-025',
    displayDay: 'Saturday',
    title: 'BlakeTheChemist',
    startISO: '2026-05-30T18:00:00-07:00',
    endISO:   '2026-05-30T19:30:00-07:00',
    venue: 'Main Stage',
    category: 'DJ',
    genre: 'Disco, House, Garage',
    panelists: [],
    description: 'A classically trained multi-instrumentalist and Icon Collective alum, Blakethechemist bridges the gap between high-level Funk and Jazztronica virtuosity and the underground rave, pioneering a unique sound that fuses technical musicianship with the hypnotic, alien energy wanted of the dance floor.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-026',
    displayDay: 'Saturday',
    title: 'DJ Matcha',
    startISO: '2026-05-30T19:00:00-07:00',
    endISO:   '2026-05-30T20:30:00-07:00',
    venue: 'Fantail',
    category: 'DJ',
    genre: 'House, Future Funk, Global',
    panelists: [],
    description: 'The doggo that throws down the dirtiest beats. DJ Matcha digs through crates like a dog with a bone, delivering digital bangers and danceable tunes.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-027',
    displayDay: 'Saturday',
    title: 'Cielo Bun',
    startISO: '2026-05-30T19:30:00-07:00',
    endISO:   '2026-05-30T21:00:00-07:00',
    venue: 'Main Stage',
    category: 'DJ',
    genre: 'Progressive House, Hardstyle, Techno, and Trance',
    panelists: [],
    description: 'Just a blue bun from the bay with a passion for music and a love of seeing people dance their hearts out. Hopefully making a difference in their lives, even if it\'s just for a moment.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-028',
    displayDay: 'Saturday',
    title: 'Dabk0ta',
    startISO: '2026-05-30T23:30:00-07:00',
    endISO:   '2026-05-31T00:30:00-07:00',
    venue: 'Fantail',
    category: 'DJ',
    genre: 'Hip Hop, Tech House, DnB',
    panelists: [],
    description: 'Hailing from Vacaville (Lack of Thrill), CA. Dabk0ta is a furry music curator like no other. Host of ROAR in Sacramento, this handsome fuzzy maestro just doesn\'t know when to quit. Bringing an amalgam of tasty hip hop, tech house, drum and bass, and other high energy tunes to a dancefloor near you.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-029',
    displayDay: 'Saturday',
    title: 'Missing Sock',
    startISO: '2026-05-30T20:30:00-07:00',
    endISO:   '2026-05-30T22:00:00-07:00',
    venue: 'Fantail',
    category: 'DJ',
    genre: 'Chicago House, French Touch, 90s-00s House',
    panelists: [],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-030',
    displayDay: 'Saturday',
    title: 'DJ YipYap',
    startISO: '2026-05-30T23:00:00-07:00',
    endISO:   '2026-05-31T00:00:00-07:00',
    venue: 'Main Stage',
    category: 'DJ',
    genre: 'Old School Happy Hardcore',
    panelists: [],
    description: 'Old school happy hardcore, straight to your dome piece. Contains: Blistering piano jams, cheeseball vocal anthems, and toxic whimsy. May cause frenzy damage.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-031',
    displayDay: 'Saturday',
    title: 'Piroko Project',
    startISO: '2026-05-30T22:00:00-07:00',
    endISO:   '2026-05-30T23:30:00-07:00',
    venue: 'Fantail',
    category: 'DJ',
    genre: 'Anime and Japanese-Adjacent Remixes',
    panelists: [],
    description: 'Piroko Project is a Bay Area-born DJ that primarily spins anime and Japanese-adjacent remixes. He started learning to DJ in 2008, originally focusing on happy hardcore and hardcore anime remixes, and was a presence at FanimeCon. In 2019, he was one of the founding members of AniClover, a 501(c)(3) charity that focuses on anime and Japanese music, performing at venues around the Bay and in Japan multiple times a year. His current mission is to bring more anime remix sets into furry conventions.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-035',
    displayDay: 'Saturday',
    title: 'DracoDubz b2b Panda Corpz',
    startISO: '2026-05-30T21:00:00-07:00',
    endISO:   '2026-05-30T22:00:00-07:00',
    venue: 'Main Stage',
    category: 'DJ',
    genre: 'Dubstep, Hybrid Trap, Hip Hop',
    panelists: [],
    description: 'DracoDubz has been a DJ in the fandom since 2017 at Bass Totem. He runs the Trashbeasts collective — a label home to many furry DJs, producers, and MCs, including his back-to-back partner Panda Corpz, a musician and DJ from Reno, NV.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-032',
    displayDay: 'Saturday',
    title: 'Nautilus',
    startISO: '2026-05-30T22:00:00-07:00',
    endISO:   '2026-05-30T23:00:00-07:00',
    venue: 'Main Stage',
    category: 'DJ',
    genre: 'Psytrance',
    panelists: [],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-033',
    displayDay: 'Saturday',
    title: 'kumo',
    startISO: '2026-05-31T00:30:00-07:00',
    endISO:   '2026-05-31T02:00:00-07:00',
    venue: 'Fantail',
    category: 'DJ',
    genre: 'Progressive House and Trance',
    panelists: [],
    description: 'Am dog who is also a DJ! Grew up in the Bay Area and have been staying around since. Spinning primarily progressive house and trance ever since starting to DJ. Hoping to make people dance and have some fun!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-034',
    displayDay: 'Saturday',
    title: 'bar code',
    startISO: '2026-05-31T00:00:00-07:00',
    endISO:   '2026-05-31T01:00:00-07:00',
    venue: 'Main Stage',
    category: 'DJ',
    genre: 'Drum & Bass, Hard Techno, Hardcore',
    panelists: [],
    description: 'Bar Code is a culmination of years of musical influence and learning from talented peers in the fandom. After keeping a close eye on the scene for years, he made his first mark at BLFC 2021, and has since performed at Further Confusion, Vancoufur, FWA, and more. Originally falling in love with house music, he\'s recently pivoted across genre and BPM, growing month over month and surprising every time.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-036',
    displayDay: 'Saturday',
    title: 'The Weed Wizard',
    startISO: '2026-05-31T01:00:00-07:00',
    endISO:   '2026-05-31T02:00:00-07:00',
    venue: 'Main Stage',
    category: 'DJ',
    genre: 'Hardstyle, Donk, Bass House, DnB, Baile Funk',
    panelists: [],
    description: 'A Magical Squirrel from the SF Bay Area here to cast irresistible dance on you all!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-bf-001',
    displayDay: 'Saturday',
    title: 'Babyfur / Little Space',
    startISO: '2026-05-30T16:00:00-07:00',
    endISO:   '2026-05-30T17:00:00-07:00',
    venue: 'BabyFur Space',
    locationDetail: null,
    category: 'Panel',
    panelists: ['Gundar'],
    description: 'Discussion on little space. What it is and how it is achieved.',
    featured: false,
    babyfur: true,
    ageRestricted: '18+',
    status: 'confirmed',
  },

  {
    id: 'sat-bf-002',
    displayDay: 'Saturday',
    title: 'Care Giving for a Babyfur / Little',
    startISO: '2026-05-30T20:00:00-07:00',
    endISO:   '2026-05-30T21:00:00-07:00',
    venue: 'BabyFur Space',
    locationDetail: null,
    category: 'Panel',
    panelists: ['Gundar'],
    description: 'How to prepare and the importance of consent. Diaper changing demonstration to be provided.',
    featured: false,
    babyfur: true,
    ageRestricted: '18+',
    status: 'confirmed',
  },

  {
    id: 'sat-039',
    displayDay: 'Saturday',
    title: 'Unleash Your Inner Animal - Meditation Workshop',
    startISO: '2026-05-30T16:00:00-07:00',
    endISO:   '2026-05-30T17:00:00-07:00',
    venue: 'Other',
    locationDetail: "Fo'c'sle (Front of Ship)",
    category: 'Activity',
    panelists: ['Cali Coyote', 'Nekol'],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-040',
    displayDay: 'Saturday',
    title: 'Pup Mosh',
    startISO: '2026-05-30T17:00:00-07:00',
    endISO:   '2026-05-30T20:00:00-07:00',
    venue: 'Other',
    locationDetail: "Fo'c'sle (Front of Ship)",
    category: 'Meetup',
    panelists: ['Cali Coyote', 'Neko'],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-038',
    displayDay: 'Saturday',
    title: 'Plural Fur Meet and Greet!',
    startISO: '2026-05-30T20:00:00-07:00',
    endISO:   '2026-05-30T21:00:00-07:00',
    venue: 'Panel Room A',
    locationDetail: 'Petty Mess',
    category: 'Meetup',
    panelists: ['Tai'],
    description: 'Ever wonder about those who feel like multiple animals in a trenchcoat? Come listen to a short blurb about the peer reviewed science and art of identity - and later mingle and make new friends!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-fantail-bar',
    displayDay: 'Saturday',
    title: 'Fantail Bar',
    startISO: '2026-05-30T19:00:00-07:00',
    endISO:   '2026-05-31T02:00:00-07:00',
    venue: 'Fantail',
    category: 'Bar',
    panelists: [],
    description: 'The Fantail Bar is open and serving drinks at the fantail.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-inflatabar',
    displayDay: 'Saturday',
    title: 'InflataBar',
    startISO: '2026-05-30T19:00:00-07:00',
    endISO:   '2026-05-31T02:00:00-07:00',
    venue: 'Main Stage',
    category: 'Bar',
    panelists: [],
    description: 'The InflataBar is open and serving drinks at the main stage.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sat-ship-tours',
    displayDay: 'Saturday',
    title: 'Ship Tours',
    startISO: '2026-05-30T10:00:00-07:00',
    endISO:   '2026-05-30T17:00:00-07:00',
    venue: 'Other',
    locationDetail: null,
    category: 'House Event',
    panelists: [],
    description: 'Sign up with Ship\'s store for a guided tour to all the behind the scene spots of the USS Hornet!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },


  // ─────────────────────────────────────────────────────────────
  // SUNDAY, May 31, 2026
  // ─────────────────────────────────────────────────────────────

  {
    id: 'sun-dealers-den',
    displayDay: 'Sunday',
    title: "Dealer's Den",
    startISO: '2026-05-31T11:00:00-07:00',
    endISO:   '2026-05-31T13:30:00-07:00',
    venue: 'Other',
    locationDetail: "Dealer's Den",
    category: 'Dealers Den',
    panelists: [],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sun-003',
    displayDay: 'Sunday',
    title: 'Change that diaper!',
    startISO: '2026-05-31T10:00:00-07:00',
    endISO:   '2026-05-31T10:30:00-07:00',
    venue: 'BabyFur Space',
    locationDetail: null,
    category: 'Panel',
    panelists: ['Honey Bear'],
    description: 'Need a change, get a change. Got a change, give a change!\nYou slept in that diaper all night, and now it\'s full and ready to be changed. No better way to make a new friend than to offer to change their diaper. Some come to this event where you can change and be changed!',
    featured: false,
    babyfur: true,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sun-001',
    displayDay: 'Sunday',
    title: 'Ship Tours',
    startISO: '2026-05-31T10:00:00-07:00',
    endISO:   '2026-05-31T17:00:00-07:00',
    venue: 'Other',
    locationDetail: null,
    category: 'House Event',
    panelists: [],
    description: 'Sign up with Ship\'s store for a guided tour to all the behind the scene spots of the USS Hornet!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },


  {
    id: 'sun-005',
    displayDay: 'Sunday',
    title: 'Historical Fiction: Writing the Past',
    startISO: '2026-05-31T11:00:00-07:00',
    endISO:   '2026-05-31T12:00:00-07:00',
    venue: 'Panel Room B',
    category: 'Panel',
    panelists: ['Kit Silver', 'Kyell Gold', 'Huskyteer'],
    description: 'This panel explores how to write historical fiction that feels as relevant now as when it was set. We\'ll discuss weaving research into character motivation, using setting as a living presence, and crafting narratives where past and present reflect and reshape each other. Join Kyell Gold and Huskyteer as they discuss why history remains a powerful source of storytelling.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sun-004',
    displayDay: 'Sunday',
    title: 'Autism the Misunderstood',
    startISO: '2026-05-31T11:00:00-07:00',
    endISO:   '2026-05-31T13:00:00-07:00',
    venue: 'Panel Room A',
    category: 'Panel',
    panelists: ['Yin Yang the Dutch Angel Dragon', 'Adam the Ambitious', 'The Forsaken Scribe'],
    description: 'Autism The Misunderstood is a panel about Autism in various aspects of life from school to the workplace and social aspects such as the Furry Fandom. Since 2019 Adam (known in fursuit as Yin Yang) has been meticulously following studies on Autism to ensure the data is as current as possible while presenting his own experiences navigating life on the Autism spectrum, as well as resources to help others understand the condition and leverage the strengths and manage the weaknesses that may come with it. Topics include: History of the Spectrum, Financial Costs and Statistics, Strengths and Weaknesses, Resources for All Phases of Life, and Potential Companies who want to help utilize our unique abilities. If time allows, attendees are invited to share their own experiences.',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sun-006',
    displayDay: 'Sunday',
    title: 'How to Recover from Post-Con Blues',
    startISO: '2026-05-31T11:00:00-07:00',
    endISO:   '2026-05-31T12:00:00-07:00',
    venue: 'Panel Room C',
    category: 'Panel',
    panelists: ['Cassie'],
    description: "You've made a lot of new friends and gone to a lot of cool panels & parties. Or maybe this convention wasn't everything you hoped it would be. As the convention winds down, your brain can wind down too. Occasionally this can manifest in what's known as \"post-con blues\" or con drop.\n\nLearn how to manage these sudden feelings of malaise to better transition into every day life. Regardless of your Galactic Camp experience, take this time to wind down and focus on the fun memories you made.",
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sun-007',
    displayDay: 'Sunday',
    title: 'Super Swap Meet',
    startISO: '2026-05-31T12:00:00-07:00',
    endISO:   '2026-05-31T14:00:00-07:00',
    venue: 'Panel Room C',
    category: 'Meetup',
    panelists: ['Sterling Noblewolf'],
    description: 'Bring your pins, stickers, sketchbooks, anything goes! Set up your shop and exchange your trinkets & wares with fellow furs!',
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

  {
    id: 'sun-010',
    displayDay: 'Sunday',
    title: 'Closing Ceremonies',
    startISO: '2026-05-31T14:00:00-07:00',
    endISO:   '2026-05-31T14:30:00-07:00',
    venue: 'Main Stage',
    category: 'House Event',
    panelists: [],
    description: null,
    featured: false,
    babyfur: false,
    ageRestricted: null,
    status: 'confirmed',
  },

];
